POST http://localhost:8080/events/4/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTM4NjAyMDAsInVzZXJJZCI6Mn0.f2glUGVeWxkTOu2VzHmOuV9nrB4XNbtLhgbBRWbu-x4
